// src/lib/components/pokemon/Recommendations.svelte
<script lang="ts">
  import { recommendations } from "$lib/state/metrics";
  import Icon from "../common/Icon.svelte";
</script>

<ul>
  {#each $recommendations as rec}
    {@const { type } = rec}
    <li class="flex items-center border-t-[1px] border-t-slate-300 p-4 first:border-t-0">
      <div class="mr-4 hidden w-[45px] text-4xl md:block" style:color={type.color}>
        <Icon name={type.icon} />
      </div>

      <div class="grow">
        <h2 style:color={type.color}>
          <span class="md:hidden">
            <Icon name={type.icon} />
          </span>
          {type.name}
        </h2>

        <div class="text-base text-gray-600">
          {(rec.ownRatio * 100).toFixed(2)}% —
          {(rec.againstRatio * 100).toFixed(2)}% of compared.
        </div>
      </div>

      {#if rec.change === "add"}
        <div class="font-bold text-red-500">
          <Icon name="square-plus" />
          Too Few
        </div>
      {:else if rec.change === "remove"}
        <div class="font-bold text-red-500">
          <Icon name="square-minus" />
          Too Many
        </div>
      {:else}
        <div class="font-bold text-lime-600">
          <Icon name="check" />
          All Good
        </div>
      {/if}
    </li>
  {/each}
</ul>

// src/components/pokemon/recommendations.tsx
import { useComputed, useSignal, useSignalEffect } from "@preact/signals";
import { Show } from "@preact/signals/utils";
import { useContext } from "preact/hooks";
import type { RecommendedChange } from "../../metrics/recommendations";
import { MetricsContext } from "../../state/context";
import { stored } from "../../utils/storage";
import { ButtonLink } from "../common/button_link";
import { Icon } from "../common/icon";
import { LinedSubheading } from "../layout/lined_subheading";

const store = stored<boolean>("stardex_recommendations_show_just_right");

export function Recommendations() {
  const showJustRight = useSignal(store.load() ?? false);

  useSignalEffect(() => {
    store.dump(showJustRight.value);
  });

  return (
    <>
      <RecommendedChangeGroup change="remove" title="Too Many" />
      <RecommendedChangeGroup change="add" title="Too Few" />

      <Show when={showJustRight}>
        <RecommendedChangeGroup change="none" title="Just Right" />
      </Show>

      <ButtonLink onClick={() => (showJustRight.value = !showJustRight.value)} small>
        {showJustRight.value ? "Hide" : "Show"} just right
      </ButtonLink>
    </>
  );
}

interface RecommendedChangeGroupProps {
  change: RecommendedChange;
  title: string;
}

function RecommendedChangeGroup({ change, title }: RecommendedChangeGroupProps) {
  const metrics = useContext(MetricsContext);
  const recommendations = useComputed(() =>
    metrics.recommendations.value.filter((r) => r.change === change),
  );

  if (recommendations.value.length === 0) {
    return null;
  }

  return (
    <div class="mb-4 last:mb-0">
      <LinedSubheading>{title}</LinedSubheading>
      {recommendations.value.map(({ type, ownRatio, againstRatio }) => (
        <li class="flex items-center p-2">
          <div class="mr-4 hidden w-11.25 text-4xl md:block" style={`color: ${type.color}`}>
            <Icon name={type.icon} />
          </div>

          <div class="grow">
            <h2 style={`color: ${type.color}`}>
              <span class="md:hidden">
                <Icon name={type.icon} />
              </span>
              {type.name}
            </h2>

            <div class="text-foreground-lesser text-base">
              {(ownRatio * 100).toFixed(2)}% — {(againstRatio * 100).toFixed(2)}% of compared.
            </div>
          </div>
        </li>
      ))}
    </div>
  );
}
