// src/components/layout/index.tsx
import type { JSXElement } from "solid-js";
import { Controls } from "./controls";
import { Footer } from "./footer";
import { Logo } from "./logo";
import { ProjectsModal, ProjectsSelect } from "./projects";
import { Toast } from "./toast";

export interface LayoutProps {
  children: JSXElement;
}

export function Layout(props: LayoutProps) {
  return (
    <>
      <div id="top" />

      <div class="flex min-h-screen flex-col">
        <div class="grow">
          <div class="sticky top-4 ml-4 hidden lg:block">
            <div class="mb-2">
              <ProjectsSelect />
            </div>
            <div class="ml-2">
              <Controls />
            </div>
          </div>
          <div class="m-auto w-200 max-w-full grow pt-8">
            <div class="mb-4 flex flex-col items-center gap-2 lg:mb-12 lg:flex-row lg:gap-3">
              <Logo />
              <h1 class="grow text-4xl font-bold text-primary">Stardex</h1>
            </div>

            <div class="mb-4 flex justify-center lg:hidden">
              <ProjectsSelect />
            </div>

            <ProjectsModal />

            {/* TODO: <Notices /> */}

            {/* <h2 class="border-y border-divider-light py-4 text-2xl font-bold text-foreground-muted">
              {activeProjectName}
            </h2> */}

            <div class="mb-8 hidden border-b-2 border-b-divider-light lg:block" />
            <main class="mx-4 md:mx-0">{props.children}</main>

            <Toast />
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
}

// src/components/layout/Layout.tsx
import type { ComponentChildren } from "preact";

export interface LayoutProps {
  left: ComponentChildren;
  right: ComponentChildren;
}

export function Layout(props: LayoutProps) {
  return (
    <div class="flex min-h-screen flex-col">
      <header class="p-4">
        <div
          title="Stardex"
          class="bg-primary flex h-13.75 w-13.75 items-center justify-center rounded-md text-3xl font-bold text-white shadow-xl shadow-slate-400 select-none"
        >
          <div>Sd</div>
        </div>
      </header>
      <div class="lg:flex">
        <Pane>{props.left}</Pane>
        <Pane>{props.right}</Pane>
      </div>
    </div>
  );
}

function Pane(props: { children: ComponentChildren }) {
  return <div class="lg:grow lg:p-4">{props.children}</div>;
}
