// src/lib/components/layout/Modal.svelte
<script lang="ts">
  import { onMount, type Snippet } from "svelte";
  import { portal } from "$lib/utils/portal";
  import hotkeys from "hotkeys-js";
  import Icon from "../common/Icon.svelte";

  interface Props {
    title: Snippet;
    children: Snippet;
    footer?: Snippet;
    close(): void;
  }

  let { title, children, footer, close }: Props = $props();

  function handleClick(e: MouseEvent) {
    if ((e.target as HTMLElement)?.parentNode === document.body) {
      close();
    }
  }

  onMount(() => {
    hotkeys("esc", close);
    return () => hotkeys.unbind("esc");
  });
</script>

<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
<div
  use:portal
  class="fixed bottom-0 left-0 z-10 flex h-screen w-screen items-end justify-center bg-black/30 lg:items-center"
  onclick={handleClick}
>
  <div
    class="flex h-[60vh] w-[500px] max-w-full flex-col overflow-y-scroll rounded-md bg-white p-8 lg:h-[unset] lg:overflow-y-auto"
  >
    <div class="mb-4 flex border-b-2 border-b-slate-700 pb-4">
      <h1 class="grow text-xl font-bold">
        {@render title()}
      </h1>

      <button class="text-slate-400" aria-label="Close" onclick={close}>
        <Icon name="times" />
      </button>
    </div>

    <div class="grow">
      {@render children()}
    </div>

    <div>
      {@render footer?.()}
    </div>
  </div>
</div>

// src/components/layout/modal.tsx
import hotkeys from "hotkeys-js";
import type { ComponentChildren } from "preact";
import { createPortal } from "preact/compat";
import { useEffect } from "preact/hooks";
import { ButtonIcon } from "../common/button_icon";

const root = document.getElementById("app-modal")!;

export interface ModalProps {
  title: ComponentChildren;
  children: ComponentChildren;
  footer?: ComponentChildren;
  onClose(): void;
}

export function Modal(props: ModalProps) {
  function handleClick(e: MouseEvent) {
    if ((e.target as HTMLElement)?.parentNode === root) {
      props.onClose();
    }
  }

  useEffect(() => {
    hotkeys("esc", props.onClose);
    return () => hotkeys.unbind("esc");
  }, [props.onClose]);

  return createPortal(
    <div
      class="fixed bottom-0 left-0 z-10 flex h-screen w-screen items-end justify-center bg-black/30 lg:items-center"
      onClick={handleClick}
    >
      <div class="bg-background flex h-[60vh] w-125 max-w-full flex-col overflow-y-scroll rounded-md p-8 lg:h-[unset] lg:overflow-y-auto">
        <div class="border-b-divider-heavy mb-4 flex border-b-2 pb-4">
          <h1 class="grow text-xl font-bold">{props.title}</h1>
          <ButtonIcon icon="times" label="Close" onClick={props.onClose} />
        </div>
        <div class="grow">{props.children}</div>
        {props.footer ? <div>{props.footer}</div> : null}
      </div>
    </div>,
    root,
  );
}
