// src/lib/components/common/TypeName.svelte
<script lang="ts">
  import { Type } from "$lib/models/type";
  import Icon from "./Icon.svelte";

  interface Props {
    for: string | Type;
  }

  let props: Props = $props();
  let type = $derived(typeof props.for === "string" ? Type.of(props.for) : props.for);
</script>

<span class="whitespace-nowrap" style="color: {type.color}">
  <span>
    <Icon name={type.icon} />
  </span>
  <span>
    {type.name}
  </span>
</span>

// src/shared/TypeName.tsx
/** @jsx jsx */
import { jsx } from "@emotion/core";
import { Type } from '../models/Type'
import Icon from './Icon'
import { capitalize } from '../helpers/string'

type Opts = 
  | { type: Type }
  | { name: string }

type Props = Opts & {
  onClick?: () => void;
}

export default function TypeName({ onClick, ...props }: Props) {
  const type = ('type' in props)
    ? props.type
    : new Type(props.name)
    
  return (
    <strong 
      onClick={onClick}
      css={{ 
        color: type.color,
        cursor: onClick ? 'pointer' : 'unset',
      }} 
    >
      <Icon src={type.icon} fw /> {capitalize(type.name)}
    </strong>
  );
}
