// src/components/layout/modal.tsx
import hotkeys from "hotkeys-js";
import type { ComponentChildren } from "preact";
import { createPortal } from "preact/compat";
import { useEffect } from "preact/hooks";
import { ButtonIcon } from "../common/button_icon";

const root = document.getElementById("app-modal")!;

export interface ModalProps {
  title: ComponentChildren;
  children: ComponentChildren;
  footer?: ComponentChildren;
  onClose(): void;
}

export function Modal(props: ModalProps) {
  function handleClick(e: MouseEvent) {
    if ((e.target as HTMLElement)?.parentNode === root) {
      props.onClose();
    }
  }

  useEffect(() => {
    hotkeys("esc", props.onClose);
    return () => hotkeys.unbind("esc");
  }, [props.onClose]);

  return createPortal(
    <div
      class="fixed bottom-0 left-0 z-10 flex h-screen w-screen items-end justify-center bg-black/(--backdrop-opacity) lg:items-center"
      onClick={handleClick}
    >
      <div class="bg-background flex h-[60vh] w-125 max-w-full flex-col overflow-y-scroll rounded-md p-8 lg:h-[unset] lg:overflow-y-auto">
        <div class="border-b-divider-heavy mb-4 flex border-b-2 pb-4">
          <h1 class="grow text-xl font-bold">{props.title}</h1>
          <ButtonIcon icon="times" label="Close" onClick={props.onClose} />
        </div>
        <div class="grow">{props.children}</div>
        {props.footer ? <div>{props.footer}</div> : null}
      </div>
    </div>,
    root,
  );
}

// src/components/common/menus/modal.tsx
import hotkeys from "hotkeys-js";
import { createEffect, onCleanup, type JSXElement } from "solid-js";
import { Portal } from "solid-js/web";
import { ButtonIcon } from "../button";

const root = document.getElementById("root-modal")!;

export interface ModalProps {
  title: JSXElement;
  children: JSXElement;
  footer?: JSXElement;
  footerHasDivider?: boolean;
  onClose(): void;
}

export function Modal(props: ModalProps) {
  function handleClick(e: MouseEvent) {
    if ((e.target as HTMLElement)?.parentNode === ref) {
      props.onClose();
    }
  }

  createEffect(() => {
    hotkeys("esc", props.onClose);
    onCleanup(() => hotkeys.unbind("esc"));
  });

  createEffect(() => {
    document.documentElement.classList.add("has-modal");
    onCleanup(() => document.documentElement.classList.remove("has-modal"));
  });

  let ref!: HTMLDivElement;

  return (
    <Portal mount={root} ref={ref}>
      <div
        class="fixed bottom-0 left-0 z-50 flex h-dvh w-screen items-end justify-center overscroll-contain bg-black/(--backdrop-opacity) lg:items-center"
        on:click={handleClick}
      >
        <div class="flex max-h-[90dvh] w-125 max-w-full flex-col overflow-y-scroll rounded-t-md bg-background p-8 lg:overflow-y-auto lg:rounded-b-md">
          <div class="mb-4 flex border-b-2 border-b-divider-heavy pb-4">
            <h1 class="grow text-xl font-bold text-secondary">{props.title}</h1>
            <ButtonIcon icon="times" label="Close" onClick={() => props.onClose()} />
          </div>
          <div class="grow">{props.children}</div>
          {props.footer ? (
            <div
              class="mt-4"
              classList={{ "border-t-2 border-t-divider-heavy pt-4": props.footerHasDivider }}
            >
              {props.footer}
            </div>
          ) : null}
        </div>
      </div>
    </Portal>
  );
}
