// src/lib/components/Modal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import Icon from "./Icon.svelte";

  interface Props {
    open: boolean;
    onclose(): void;
    title: string;
    children: Snippet;
  }

  let { open, onclose, title, children }: Props = $props();
  let dialog = $state<HTMLDialogElement>();

  $effect(() => {
    if (open) dialog?.showModal();
  });

  $effect(() => {
    document.body.classList[open ? "add" : "remove"]("overflow-hidden");
  });

  function onclick(e: MouseEvent) {
    if (e.target === dialog) dialog.close();
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions -->
<dialog
  class="mb-0 hidden max-w-full items-center justify-center open:block md:mb-auto"
  bind:this={dialog}
  {onclose}
  {onclick}
>
  <div class="h-[70vh] w-[500px] max-w-full p-8 md:h-[unset]">
    <div class="mb-4 flex border-b-2 border-b-slate-700 pb-4">
      <h1 class="grow text-xl font-bold">
        {title}
      </h1>

      <button class="text-slate-400" aria-label="Close" onclick={() => dialog?.close()}>
        <Icon name="times" />
      </button>
    </div>

    {@render children()}
  </div>
</dialog>

// src/components/common/menus/modal.tsx
import hotkeys from "hotkeys-js";
import { createEffect, onCleanup, type JSXElement } from "solid-js";
import { Portal } from "solid-js/web";
import { ButtonIcon } from "../button";

const root = document.getElementById("root-modal")!;

export interface ModalProps {
  title: JSXElement;
  children: JSXElement;
  footer?: JSXElement;
  footerHasDivider?: boolean;
  onClose(): void;
}

export function Modal(props: ModalProps) {
  function handleClick(e: MouseEvent) {
    if ((e.target as HTMLElement)?.parentNode === ref) {
      props.onClose();
    }
  }

  createEffect(() => {
    hotkeys("esc", props.onClose);
    onCleanup(() => hotkeys.unbind("esc"));
  });

  createEffect(() => {
    document.documentElement.classList.add("has-modal");
    onCleanup(() => document.documentElement.classList.remove("has-modal"));
  });

  let ref!: HTMLDivElement;

  return (
    <Portal mount={root} ref={ref}>
      <div
        class="fixed bottom-0 left-0 z-50 flex h-dvh w-screen items-end justify-center overscroll-contain bg-black/(--backdrop-opacity) lg:items-center"
        on:click={handleClick}
      >
        <div class="flex max-h-[90dvh] w-125 max-w-full flex-col overflow-y-scroll rounded-t-md bg-background p-8 lg:overflow-y-auto lg:rounded-b-md">
          <div class="mb-4 flex border-b-2 border-b-divider-heavy pb-4">
            <h1 class="grow text-xl font-bold text-secondary">{props.title}</h1>
            <ButtonIcon icon="times" label="Close" onClick={() => props.onClose()} />
          </div>
          <div class="grow">{props.children}</div>
          {props.footer ? (
            <div
              class="mt-4"
              classList={{ "border-t-2 border-t-divider-heavy pt-4": props.footerHasDivider }}
            >
              {props.footer}
            </div>
          ) : null}
        </div>
      </div>
    </Portal>
  );
}
