// src/lib/components/common/TypeName.svelte
<script lang="ts">
  import { Type } from "$lib/models/type";
  import Icon from "./Icon.svelte";

  interface Props {
    for: string | Type;
  }

  let props: Props = $props();
  let type = $derived(typeof props.for === "string" ? Type.of(props.for) : props.for);
</script>

<span class="whitespace-nowrap" style="color: {type.color}">
  <span>
    <Icon name={type.icon} />
  </span>
  <span>
    {type.name}
  </span>
</span>

// src/TypeName.tsx
import React from 'react'
import { Type } from './models/Type'
import Icon from './Icon'
import { capitalize } from './helpers/string'

type Props = 
  | { type: Type }
  | { name: string }

export default function TypeName(props: Props) {
  const type = ('type' in props)
    ? props.type
    : new Type(props.name)
    
  return (
    <strong style={{ color: type.color }}>
      <Icon src={type.icon} fw /> {capitalize(type.name)}
    </strong>
  );
}
