// src/TypeName.tsx
import React from 'react'
import { Type } from './models/Type'
import Icon from './Icon'
import { capitalize } from './helpers/string'

type Props = 
  | { type: Type }
  | { name: string }

export default function TypeName(props: Props) {
  const type = ('type' in props)
    ? props.type
    : new Type(props.name)
    
  return (
    <strong style={{ color: type.color }}>
      <Icon src={type.icon} fw /> {capitalize(type.name)}
    </strong>
  );
}

// src/lib/components/TypeName.svelte
<script lang="ts">
  import { resolveType } from "$lib/models/type";
  import Icon from "./Icon.svelte";

  interface Props {
    for: string;
  }

  let props: Props = $props();
  let type = $derived(resolveType(props.for));
</script>

<span style="color: {type.color}">
  <span>
    <Icon name={type.icon} />
  </span>
  <span>
    {type.name}
  </span>
</span>
