// src/components/layout/index.tsx
import type { JSXElement } from "solid-js";
import { Controls } from "./controls";
import { Footer } from "./footer";
import { Logo } from "./logo";
import { ProjectsModal, ProjectsSelect } from "./projects";
import { Toast } from "./toast";

export interface LayoutProps {
  children: JSXElement;
}

export function Layout(props: LayoutProps) {
  return (
    <>
      <div id="top" />

      <div class="flex min-h-screen flex-col">
        <div class="grow">
          <div class="sticky top-4 ml-4 hidden lg:block">
            <div class="mb-2">
              <ProjectsSelect />
            </div>
            <div class="ml-2">
              <Controls />
            </div>
          </div>
          <div class="m-auto w-200 max-w-full grow pt-8">
            <div class="mb-4 flex flex-col items-center gap-2 lg:mb-12 lg:flex-row lg:gap-3">
              <Logo />
              <h1 class="grow text-4xl font-bold text-primary">Stardex</h1>
            </div>

            <div class="mb-4 flex justify-center lg:hidden">
              <ProjectsSelect />
            </div>

            <ProjectsModal />

            {/* TODO: <Notices /> */}

            {/* <h2 class="border-y border-divider-light py-4 text-2xl font-bold text-foreground-muted">
              {activeProjectName}
            </h2> */}

            <div class="mb-8 hidden border-b-2 border-b-divider-light lg:block" />
            <main class="mx-4 md:mx-0">{props.children}</main>

            <Toast />
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
}

// src/lib/components/layout/Layout.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import Nav from "./Nav.svelte";
  import Logo from "./Logo.svelte";
  import Footer from "./Footer.svelte";
  import QuickProjects from "./QuickProjects.svelte";

  interface Props {
    title: string;
    children: Snippet;
  }

  let { title, children }: Props = $props();
</script>

<div class="sticky top-4 ml-4 hidden items-center gap-4 lg:flex">
  <Logo />
  <QuickProjects />
</div>

<div class="m-auto w-[800px] max-w-full pt-8">
  <div class="mb-4 flex justify-center md:justify-start lg:hidden">
    <Logo />
  </div>

  <div class="mb-8">
    <h1 class="grow text-center text-4xl font-bold md:text-left">
      {title}
    </h1>
  </div>

  <Nav />

  <main class="mx-4 md:mx-0">
    {@render children()}
  </main>

  <Footer />
</div>
