// src/components/layout/section.tsx
import type { ComponentChildren } from "preact";

export interface SectionProps {
  id: string;
  title: string;
  children: ComponentChildren;
  hasActions?: boolean;
}

export function Section({ id, title, children, hasActions }: SectionProps) {
  return (
    <section id={id} class="border-b-divider-light relative mb-8 border-b pb-8">
      <h2 class={`grow text-3xl ${hasActions ? "mb-2" : "mb-8"}`}>{title}</h2>
      <div>{children}</div>
    </section>
  );
}

// src/lib/components/layout/Section.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    title: string;
    children: Snippet;
  }

  let { title, children }: Props = $props();
</script>

<section class="mb-8 border-b-[1px] border-b-slate-300 pb-8 last:border-b-0">
  <h2 class="mb-8 text-3xl">
    {title}
  </h2>

  <div>
    {@render children()}
  </div>
</section>
